import React, { useState, useEffect } from "react";
import { View, StyleSheet, ScrollView, Share, Alert } from "react-native";
import { Text, Card, Divider, Button, useTheme } from "react-native-paper";
import {
  FileText,
  User,
  Heart,
  Activity,
  Droplet,
  Calendar,
  Pill,
} from "lucide-react-native";
import AsyncStorage from "../utils/asyncStorage";
import { useTranslation } from "react-i18next";
import { useAuth } from "../utils/AuthContext";

const HealthReportScreen = () => {
  const { t } = useTranslation();
  const { user } = useAuth();
  const [data, setData] = useState({
    bmi: "N/A",
    water: 0,
    bp: "N/A",
    appointments: 0,
    vaccines: 0,
    medicines: [],
  });

  useEffect(() => {
    loadSummary();
  }, []);

  const loadSummary = async () => {
    try {
      const today = new Date().toLocaleDateString();
      const water = await AsyncStorage.getItem(`water_${today}`);
      const bpLogs = await AsyncStorage.getItem("bp_logs");
      const apps = await AsyncStorage.getItem("appointments");
      const vaccines = await AsyncStorage.getItem("user_vaccines");
      const meds = await AsyncStorage.getItem("user_medicines");
      const storedBmi = await AsyncStorage.getItem("user_bmi");

      const bp = bpLogs ? JSON.parse(bpLogs)[0] : null;
      const appCount = apps ? JSON.parse(apps).length : 0;
      const vacCount = vaccines
        ? JSON.parse(vaccines).filter((v) => v.done).length
        : 0;
      const medicineList = meds ? JSON.parse(meds) : [];

      setData({
        bmi: storedBmi || "N/A",
        water: water || 0,
        bp: bp ? `${bp.systolic}/${bp.diastolic}` : "N/A",
        appointments: appCount,
        vaccines: vacCount,
        medicines: medicineList,
      });
    } catch (e) {
      console.error(e);
    }
  };

  const handleShare = async () => {
    try {
      const summary = `
--- ${t("health_summary")} ---
${t("date")}: ${new Date().toLocaleDateString()}
${t("name")}: ${user?.name || "User"}

1. ${t("bmi_calculator")}: ${data.bmi}
2. ${t("blood_pressure")}: ${data.bp}
3. ${t("water_intake")}: ${data.water} ${t("glasses")}
4. ${t("vaccines_completed")}: ${data.vaccines}
5. ${t("upcoming_appointments")}: ${data.appointments}

${t("medicines")}:
${data.medicines.map((m) => `- ${m.name} (${m.time})`).join("\n")}

Generated by Virtual Doctor App
      `;

      await Share.share({
        message: summary,
        title: t("health_summary"),
      });
    } catch (error) {
      Alert.alert("Error", error.message);
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Card style={styles.headerCard}>
        <Card.Content style={styles.center}>
          <FileText size={48} color="#6B7FFF" />
          <Text variant="headlineSmall" style={styles.title}>
            {t("health_summary")}
          </Text>
          <Text variant="bodySmall">{new Date().toLocaleDateString()}</Text>
        </Card.Content>
      </Card>

      <Card style={styles.sectionCard}>
        <Card.Content>
          <View style={styles.row}>
            <User size={20} color="#666" />
            <Text variant="titleMedium" style={styles.sectionTitle}>
              {t("personal_info")}
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Text>{t("name")}</Text>
            <Text style={styles.bold}>{user?.name}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text>{t("bmi_calculator")}</Text>
            <Text style={styles.bold}>{data.bmi}</Text>
          </View>
        </Card.Content>
      </Card>

      <Card style={styles.sectionCard}>
        <Card.Content>
          <View style={styles.row}>
            <Activity size={20} color="#FF9DCC" />
            <Text variant="titleMedium" style={styles.sectionTitle}>
              {t("daily_vitals")}
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Text>{t("last_bp")}</Text>
            <Text style={styles.bold}>{data.bp}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text>{t("water_intake")}</Text>
            <Text style={styles.bold}>
              {data.water} {t("glasses")}
            </Text>
          </View>
        </Card.Content>
      </Card>

      <Card style={styles.sectionCard}>
        <Card.Content>
          <View style={styles.row}>
            <Pill size={20} color="#8FE0C3" />
            <Text variant="titleMedium" style={styles.sectionTitle}>
              {t("medicines")}
            </Text>
          </View>
          {data.medicines.length === 0 ? (
            <Text style={styles.emptyText}>{t("no_medicines")}</Text>
          ) : (
            data.medicines.map((m, i) => (
              <View key={i} style={styles.infoRow}>
                <Text>{m.name}</Text>
                <Text style={styles.bold}>{m.time}</Text>
              </View>
            ))
          )}
        </Card.Content>
      </Card>

      <Button
        mode="contained"
        icon="share"
        style={styles.shareBtn}
        onPress={handleShare}
      >
        {t("share_report")}
      </Button>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  content: { padding: 16 },
  headerCard: { borderRadius: 20, marginBottom: 20, backgroundColor: "#FFF" },
  center: { alignItems: "center", paddingVertical: 20 },
  title: { fontWeight: "bold", marginTop: 10 },
  sectionCard: { borderRadius: 16, marginBottom: 12 },
  row: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  sectionTitle: { marginLeft: 12, fontWeight: "bold" },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  bold: { fontWeight: "bold", color: "#333" },
  shareBtn: {
    marginTop: 20,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    backgroundColor: "#6B7FFF",
  },
});

export default HealthReportScreen;
